### ISSUE TITLE
Problems with .dat file having 90> levels

### ISSUE THREAD

**Issue by aazimuthh** [gd-edit/GDE#102]
Basically, having anything higher than 90 from what I've seen causes gd-edit to stay on the "Loading" phase for about 10 minutes, didn't let it go on longer than that, dunno if its infinite or not.

**Comment by AlFasGD** [comment]
There was a bug in the implementation that would cause an error during loading, causing it to never finish. Try compiling the current `master` if you can and run. Should the problem persist, I would kindly ask for the .dat file to test for myself if that's okay.

**Comment by AlFasGD** [comment]
Perhaps this is no longer relevant, considering that the loading has been optimized to be more both computer- and user-friendly. Please run the current `master` again and confirm that this is not the case, so that the issue be closed. Otherwise, we will require more information per the issue, including logs and perhaps the CCLocalLevels.dat for local insection.
