### ISSUE TITLE
Startpos desync

### ISSUE THREAD

**Issue by Dominuus** [gd-edit/GDE#133]
I've been working on a solo level in the original game and it's always really annoying when there's startpos desync issues, it's gotten so bad to the point were when I use a startpos, the song gets delayed by a whole second and it makes it a pain in the ass to sync gameplay and pulses, I don't know if that has been fixed or not, but if not, please try to do something about it. I'm also no programmer, although I intend to be someday, so I don't know how exactly you'd handle stuff like that, but I think it should be possible.

**Comment by Altenhh** [comment]
just a reminder that this is a **seperate** instance from the normal gd editor, this would mean that we can do whatever we want to either optimize or slow down the whole entire application. ill consider this as a performance issue though.

**Comment by AlFasGD** [comment]
The way GD itself handles audio is not our business. GDE will be based on the libraries provided by osu-framework, which uses BASS AFAIK. Music playback should be good enough to stay consistent throughout the entire level. The way Start Pos are going to be handled will be more optimized than GD itself, since we are all aware of the annoying unoptimized calculations that are performed every single attempt. Since this is not an issue, neither intended to be, this issue will be closed. Only consider opening such an issue if this is an actual issue when implemented in GDE.
